dataset:
  args: [c4, en]
  kwargs: {split: train}

tokenizer:
  args: [bert-base-uncased]
  kwargs: {}

data:
  length: 512
  min_length: 384
  pad_token_id: 0
  batch_size: 32
  shuffle_buffer_size: 25_000

model:
  num_layers: 12
  vocabulary_size: 32_768
  embedding_dim: 384
  model_dim: 768
  num_heads: 12
  pos_emb_portion: 0.5
  hidden_dim: 3_072
  dropout: 0.0

optimizer:
  gradient_accumulation_steps: [[0, 1], [10_000, 2], [25_000, 8], [50_000, 32]]
  weight_decay: 0.01
  lr_min: 0.00006
  lr_max: 0.0006
  lr_decay_steps: 500_000
  lr_warmup_steps: 1_000
  gradient_clip_norm: 1.0
  adam_b1: 0.9
  adam_b2: 0.999

mixed_precision:
  enable: true
  initial_scale_log2: 8
  scale_period: 5000
