dataset:
  - args: [c4, en]
    kwargs: {split: train}
    weight: 1
  - args: [wikitext, wikitext-103-raw-v1]
    kwargs: {split: train}
    weight: 0.1

tokenizer:
  args: [bert-base-uncased]
  kwargs: {}

data:
  length: 128
  min_length: 96
  pad_token_id: 0
  batch_size: 32
  shuffle_buffer_size: 1_000

model:
  num_layers: 6
  vocabulary_size: 32_768
  embedding_dim: 128
  model_dim: 384
  num_heads: 3
  pos_emb_portion: 0.5
  hidden_dim: 1_536
  dropout: 0.0

optimizer:
  gradient_accumulation_steps: [[0, 1]]
  weight_decay: 0.002
  lr_min: 0.0002
  lr_max: 0.002
  lr_decay_steps: 10_000
  lr_warmup_steps: 100
  gradient_clip_norm: 1.0
  adam_b1: 0.9
  adam_b2: 0.999

mixed_precision:
  enable: true
  initial_scale_log2: 8
  scale_period: 1000
