# Config to train a new tokenizer on the C4 dataset.

dataset:
  huggingface:
    args: [c4, en]
    kwargs: {split: train}
    streaming: true
  buffering:
    buffer_size: 1000
    timeout: 0.1
  tokenizer: null
  shuffle: null


tokenizer:
  vocabulary_size: 8192  # 2**13
  min_token_frequency: 100
  max_samples: 10_000_000
  key: text
  path: ./tokenizers/c4-en-8192.json
